controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
submit_exercise:
    path: '/submit-exercise'
    controller: App\Controller\ExerciseController::submitExercise